repos:
  - repo: local
    hooks:
      - id: gray
        name: gray
        entry: gray
        language: python
        language_version: python3
        require_serial: true
        types: [python]
