# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - TOX_ENV=py36
  - TOX_ENV=py37
  - TOX_ENV=py38

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV
